#ifndef INSTRS_H__
#define INSTRS_H__ 1

/* DO NOT EDIT!
 *
 * This file is created automatically by make_func from
 * the specifications in func_spec.
 *
 * It holds the bytecode values for all machine instructions, plus
 * declarations of the tables holding information about the instructions.
 */

#include "exec.h"  /* struct instr_s == instr_t */

#define CODE_OFFSET  (0)
#define CODE_COUNT   (181)
  /* First offset and number of internal opcodes.
   */

#define EFUN_OFFSET  (181)
#define EFUN_COUNT   (23)
  /* First offset and number of efun opcodes.
   */

#define EFUN0_OFFSET  (204)
#define EFUN0_COUNT   (14)
  /* First offset and number of efun0 opcodes.
   */

#define EFUN1_OFFSET  (218)
#define EFUN1_COUNT   (85)
  /* First offset and number of efun1 opcodes.
   */

#define EFUN2_OFFSET  (303)
#define EFUN2_COUNT   (49)
  /* First offset and number of efun2 opcodes.
   */

#define EFUN3_OFFSET  (352)
#define EFUN3_COUNT   (15)
  /* First offset and number of efun3 opcodes.
   */

#define EFUN4_OFFSET  (367)
#define EFUN4_COUNT   (1)
  /* First offset and number of efun4 opcodes.
   */

#define EFUNV_OFFSET  (368)
#define EFUNV_COUNT   (62)
  /* First offset and number of efunv opcodes.
   */

#define LAST_INSTRUCTION_CODE (429)
  /* The highest token value in use.
   */

#define TEFUN_OFFSET EFUN0_OFFSET
  /* Offset of the first tabled efun.
   */

extern instr_t instrs[];
extern short efun_aliases[];
extern fulltype_t efun_arg_types[];
extern long efun_lpc_types[];
extern svalue_t *(*efun_table[])(svalue_t *);
extern svalue_t *(*vefun_table[])(svalue_t *, int);
  /* All tables are defined in efun_defs.c and compiled into lex.c
   * TODO: We might as well create efun_defs.h and compile it separately.
   */

/* --- codes --- */

#define F_ILLEGAL                      (0)
#define F_UNDEF                        (1)
#define F_EFUN0                        (2)
#define F_EFUN1                        (3)
#define F_EFUN2                        (4)
#define F_EFUN3                        (5)
#define F_EFUN4                        (6)
#define F_EFUNV                        (7)
#define F_IDENTIFIER                   (8)
#define F_STRING                       (9)
#define F_CSTRING0                     (10)
#define F_CSTRING1                     (11)
#define F_CSTRING2                     (12)
#define F_CSTRING3                     (13)
#define F_NUMBER                       (14)
#define F_CONST0                       (15)
#define F_CONST1                       (16)
#define F_NCONST1                      (17)
#define F_CLIT                         (18)
#define F_NCLIT                        (19)
#define F_FCONST0                      (20)
#define F_FLOAT                        (21)
#define F_CLOSURE                      (22)
#define F_SYMBOL                       (23)
#define F_RETURN                       (24)
#define F_RETURN0                      (25)
#define F_DEFAULT_RETURN               (26)
#define F_BREAK                        (27)
#define F_SWITCH                       (28)
#define F_SSCANF                       (29)
#define F_PARSE_COMMAND                (30)
#define F_LOCAL                        (31)
#define F_CATCH                        (32)
#define F_INC                          (33)
#define F_DEC                          (34)
#define F_POST_INC                     (35)
#define F_POST_DEC                     (36)
#define F_PRE_INC                      (37)
#define F_PRE_DEC                      (38)
#define F_LAND                         (39)
#define F_LOR                          (40)
#define F_ASSIGN                       (41)
#define F_VOID_ASSIGN                  (42)
#define F_ADD                          (43)
#define F_SUBTRACT                     (44)
#define F_MULTIPLY                     (45)
#define F_DIVIDE                       (46)
#define F_MOD                          (47)
#define F_GT                           (48)
#define F_GE                           (49)
#define F_LT                           (50)
#define F_LE                           (51)
#define F_EQ                           (52)
#define F_NE                           (53)
#define F_COMPL                        (54)
#define F_AND                          (55)
#define F_OR                           (56)
#define F_XOR                          (57)
#define F_LSH                          (58)
#define F_RSH                          (59)
#define F_RSHL                         (60)
#define F_NOT                          (61)
#define F_INDEX                        (62)
#define F_RINDEX                       (63)
#define F_AINDEX                       (64)
#define F_MAP_INDEX                    (65)
#define F_S_INDEX                      (66)
#define F_RANGE                        (67)
#define F_NR_RANGE                     (68)
#define F_RN_RANGE                     (69)
#define F_RR_RANGE                     (70)
#define F_NA_RANGE                     (71)
#define F_RA_RANGE                     (72)
#define F_AN_RANGE                     (73)
#define F_AR_RANGE                     (74)
#define F_AA_RANGE                     (75)
#define F_NX_RANGE                     (76)
#define F_RX_RANGE                     (77)
#define F_AX_RANGE                     (78)
#define F_VOID_ADD_EQ                  (79)
#define F_ADD_EQ                       (80)
#define F_SUB_EQ                       (81)
#define F_DIV_EQ                       (82)
#define F_MULT_EQ                      (83)
#define F_MOD_EQ                       (84)
#define F_AND_EQ                       (85)
#define F_OR_EQ                        (86)
#define F_XOR_EQ                       (87)
#define F_LSH_EQ                       (88)
#define F_RSH_EQ                       (89)
#define F_RSHL_EQ                      (90)
#define F_LAND_EQ                      (91)
#define F_LOR_EQ                       (92)
#define F_POP_VALUE                    (93)
#define F_POP_SECOND                   (94)
#define F_DUP                          (95)
#define F_LDUP                         (96)
#define F_SWAP_VALUES                  (97)
#define F_CLEAR_LOCALS                 (98)
#define F_SAVE_ARG_FRAME               (99)
#define F_RESTORE_ARG_FRAME            (100)
#define F_USE_ARG_FRAME                (101)
#define F_FLATTEN_XARG                 (102)
#define F_FBRANCH                      (103)
#define F_LBRANCH                      (104)
#define F_LBRANCH_WHEN_ZERO            (105)
#define F_LBRANCH_WHEN_NON_ZERO        (106)
#define F_BRANCH                       (107)
#define F_BRANCH_WHEN_ZERO             (108)
#define F_BRANCH_WHEN_NON_ZERO         (109)
#define F_BBRANCH_WHEN_ZERO            (110)
#define F_BBRANCH_WHEN_NON_ZERO        (111)
#define F_CALL_FUNCTION                (112)
#define F_CALL_INHERITED               (113)
#define F_CALL_INHERITED_NOARGS        (114)
#define F_CALL_CLOSURE                 (115)
#define F_CONTEXT_CLOSURE              (116)
#define F_CONTEXT_IDENTIFIER           (117)
#define F_PUSH_CONTEXT_LVALUE          (118)
#define F_CONTEXT_IDENTIFIER16         (119)
#define F_PUSH_CONTEXT16_LVALUE        (120)
#define F_PUSH_IDENTIFIER_LVALUE       (121)
#define F_VIRTUAL_VARIABLE             (122)
#define F_PUSH_VIRTUAL_VARIABLE_LVALUE (123)
#define F_IDENTIFIER16                 (124)
#define F_PUSH_IDENTIFIER16_LVALUE     (125)
#define F_PUSH_LOCAL_VARIABLE_LVALUE   (126)
#define F_INDEX_LVALUE                 (127)
#define F_RINDEX_LVALUE                (128)
#define F_AINDEX_LVALUE                (129)
#define F_S_INDEX_LVALUE               (130)
#define F_RANGE_LVALUE                 (131)
#define F_NR_RANGE_LVALUE              (132)
#define F_RN_RANGE_LVALUE              (133)
#define F_RR_RANGE_LVALUE              (134)
#define F_NA_RANGE_LVALUE              (135)
#define F_RA_RANGE_LVALUE              (136)
#define F_AN_RANGE_LVALUE              (137)
#define F_AR_RANGE_LVALUE              (138)
#define F_AA_RANGE_LVALUE              (139)
#define F_NX_RANGE_LVALUE              (140)
#define F_RX_RANGE_LVALUE              (141)
#define F_AX_RANGE_LVALUE              (142)
#define F_MAP_INDEX_LVALUE             (143)
#define F_MAKE_PROTECTED               (144)
#define F_MAKE_RVALUE                  (145)
#define F_PUSH_VIRTUAL_VARIABLE_VLVALUE (146)
#define F_PUSH_IDENTIFIER_VLVALUE      (147)
#define F_PUSH_IDENTIFIER16_VLVALUE    (148)
#define F_PUSH_CONTEXT_VLVALUE         (149)
#define F_PUSH_LOCAL_VARIABLE_VLVALUE  (150)
#define F_INDEX_VLVALUE                (151)
#define F_RINDEX_VLVALUE               (152)
#define F_AINDEX_VLVALUE               (153)
#define F_S_INDEX_VLVALUE              (154)
#define F_MAP_INDEX_VLVALUE            (155)
#define F_SIMUL_EFUN                   (156)
#define F_AGGREGATE                    (157)
#define F_M_AGGREGATE                  (158)
#define F_M_CAGGREGATE                 (159)
#define F_S_AGGREGATE                  (160)
#define F_S_M_AGGREGATE                (161)
#define F_PREVIOUS_OBJECT0             (162)
#define F_LAMBDA_CCONSTANT             (163)
#define F_LAMBDA_CONSTANT              (164)
#define F_FOREACH                      (165)
#define F_FOREACH_REF                  (166)
#define F_FOREACH_RANGE                (167)
#define F_FOREACH_NEXT                 (168)
#define F_FOREACH_END                  (169)
#define F_END_CATCH                    (170)
#define F_BREAK_CONTINUE               (171)
#define F_BREAKN_CONTINUE              (172)
#define F_JUMP                         (173)
#define F_NO_WARN_DEPRECATED           (174)
#define F_ARRAY_RANGE_CHECK            (175)
#define F_ARRAY0                       (176)
#define F_MOVE_VALUE                   (177)
#define F_DUP_N                        (178)
#define F_POP_N                        (179)
#define F_PUT_ARRAY_ELEMENT            (180)

/* --- efuns --- */

#define F_CALL_DIRECT                  (181)
#define F_CALL_OTHER                   (182)
#define F_CLONEP                       (183)
#define F_CLOSUREP                     (184)
#define F_EXTERN_CALL                  (185)
#define F_FLOATP                       (186)
#define F_INTP                         (187)
#define F_MAPPINGP                     (188)
#define F_MASTER                       (189)
#define F_NEGATE                       (190)
#define F_OBJECTP                      (191)
#define F_POINTERP                     (192)
#define F_RAISE_ERROR                  (193)
#define F_REFERENCEP                   (194)
#define F_SIZEOF                       (195)
#define F_STRINGP                      (196)
#define F_STRUCTP                      (197)
#define F_SYMBOLP                      (198)
#define F_THIS_INTERACTIVE             (199)
#define F_THIS_OBJECT                  (200)
#define F_THIS_PLAYER                  (201)
#define F_THROW                        (202)
#define F_TYPEOF                       (203)

/* --- efun0s --- */

#define F_CALL_OUT_INFO                (204)
#define F_CALLER_STACK_DEPTH           (205)
#define F_COMMAND_STACK                (206)
#define F_COMMAND_STACK_DEPTH          (207)
#define F_GET_EVAL_COST                (208)
#define F_HEART_BEAT_INFO              (209)
#define F_QUERY_COMMAND                (210)
#define F_REGEXP_PACKAGE               (211)
#define F_RUSAGE                       (212)
#define F_TIME                         (213)
#define F_UNSHADOW                     (214)
#define F_USERS                        (215)
#define F_UTIME                        (216)
#define F_WIZLIST_INFO                 (217)

/* --- efun1s --- */

#define F_ABS                          (218)
#define F_ACOS                         (219)
#define F_ALL_INVENTORY                (220)
#define F_ASIN                         (221)
#define F_ATAN                         (222)
#define F_BLUEPRINT                    (223)
#define F_CALLER_STACK                 (224)
#define F_CAPITALIZE                   (225)
#define F_CEIL                         (226)
#define F_CLONE_OBJECT                 (227)
#define F_COPY                         (228)
#define F_COS                          (229)
#define F_COUNT_BITS                   (230)
#define F_CTIME                        (231)
#define F_DEEP_COPY                    (232)
#define F_DESTRUCT                     (233)
#define F_DRIVER_INFO                  (234)
#define F_EXP                          (235)
#define F_FILE_SIZE                    (236)
#define F_FIND_CALL_OUT                (237)
#define F_FIND_OBJECT                  (238)
#define F_FIRST_INVENTORY              (239)
#define F_FLOOR                        (240)
#define F_GET_EXTRA_WIZINFO            (241)
#define F_GETEUID                      (242)
#define F_GETUID                       (243)
#define F_GMTIME                       (244)
#define F_IDNA_TO_ASCII                (245)
#define F_IDNA_TO_UNICODE              (246)
#define F_INPUT_TO_INFO                (247)
#define F_INTERACTIVE                  (248)
#define F_INVERT_BITS                  (249)
#define F_LAST_BIT                     (250)
#define F_LIVING                       (251)
#define F_LOAD_NAME                    (252)
#define F_LOAD_OBJECT                  (253)
#define F_LOCALTIME                    (254)
#define F_LOG                          (255)
#define F_LOWER_CASE                   (256)
#define F_M_INDICES                    (257)
#define F_MAKE_SHARED_STRING           (258)
#define F_MKDIR                        (259)
#define F_MKTIME                       (260)
#define F_NEXT_INVENTORY               (261)
#define F_NOTIFY_FAIL                  (262)
#define F_OBJECT_NAME                  (263)
#define F_OBJECT_TIME                  (264)
#define F_PREVIOUS_OBJECT              (265)
#define F_PROCESS_STRING               (266)
#define F_PROGRAM_NAME                 (267)
#define F_PROGRAM_TIME                 (268)
#define F_QUERY_NOTIFY_FAIL            (269)
#define F_QUERY_VERB                   (270)
#define F_QUOTE                        (271)
#define F_RANDOM                       (272)
#define F_REMOVE_CALL_OUT              (273)
#define F_REMOVE_INTERACTIVE           (274)
#define F_RESTORE_OBJECT               (275)
#define F_RESTORE_VALUE                (276)
#define F_REVERSE                      (277)
#define F_RM                           (278)
#define F_RMDIR                        (279)
#define F_SET_NEXT_RESET               (280)
#define F_SET_THIS_OBJECT              (281)
#define F_SET_THIS_PLAYER              (282)
#define F_SGN                          (283)
#define F_SHADOW                       (284)
#define F_SHUTDOWN                     (285)
#define F_SIN                          (286)
#define F_SQRT                         (287)
#define F_SYMBOL_VARIABLE              (288)
#define F_TAN                          (289)
#define F_TO_ARRAY                     (290)
#define F_TO_FLOAT                     (291)
#define F_TO_INT                       (292)
#define F_TO_OBJECT                    (293)
#define F_TO_STRING                    (294)
#define F_TRACE                        (295)
#define F_TRACEPREFIX                  (296)
#define F_TRANSPOSE_ARRAY              (297)
#define F_UNMKMAPPING                  (298)
#define F_UNQUOTE                      (299)
#define F_UPPER_CASE                   (300)
#define F_WIDTHOF                      (301)
#define F_WRITE                        (302)

/* --- efun2s --- */

#define F_AND_BITS                     (303)
#define F_ATAN2                        (304)
#define F_ATTACH_ERQ_DEMON             (305)
#define F_BASEOF                       (306)
#define F_BINARY_MESSAGE               (307)
#define F_CLEAR_BIT                    (308)
#define F_CONFIGURE_DRIVER             (309)
#define F_COPY_FILE                    (310)
#define F_CRYPT                        (311)
#define F_DEBUG_MESSAGE                (312)
#define F_DUMP_DRIVER_INFO             (313)
#define F_EXEC                         (314)
#define F_EXPAND_DEFINE                (315)
#define F_EXPLODE                      (316)
#define F_FUNCTIONLIST                 (317)
#define F_GET_DIR                      (318)
#define F_GET_ERROR_FILE               (319)
#define F_IMPLODE                      (320)
#define F_INTERACTIVE_INFO             (321)
#define F_LAMBDA                       (322)
#define F_LAST_INSTRUCTIONS            (323)
#define F_M_ALLOCATE                   (324)
#define F_M_DELETE                     (325)
#define F_M_ENTRY                      (326)
#define F_M_REALLOCATE                 (327)
#define F_M_VALUES                     (328)
#define F_MATCH_COMMAND                (329)
#define F_MD5_CRYPT                    (330)
#define F_MOVE_OBJECT                  (331)
#define F_NET_CONNECT                  (332)
#define F_OBJECT_INFO                  (333)
#define F_OR_BITS                      (334)
#define F_POW                          (335)
#define F_QUERY_ACTIONS                (336)
#define F_REMOVE_ACTION                (337)
#define F_RENAME                       (338)
#define F_RENAME_OBJECT                (339)
#define F_SET_BIT                      (340)
#define F_SET_DRIVER_HOOK              (341)
#define F_SET_ENVIRONMENT              (342)
#define F_SET_EXTRA_WIZINFO            (343)
#define F_STRUCT_INFO                  (344)
#define F_SYMBOL_FUNCTION              (345)
#define F_TELL_OBJECT                  (346)
#define F_TEST_BIT                     (347)
#define F_TRANSFER                     (348)
#define F_UNBOUND_LAMBDA               (349)
#define F_VARIABLE_LIST                (350)
#define F_XOR_BITS                     (351)

/* --- efun3s --- */

#define F_CONFIGURE_INTERACTIVE        (352)
#define F_CONFIGURE_OBJECT             (353)
#define F_CONVERT_CHARSET              (354)
#define F_EXECUTE_COMMAND              (355)
#define F_HMAC                         (356)
#define F_IDNA_STRINGPREP              (357)
#define F_NEXT_BIT                     (358)
#define F_REGEXP                       (359)
#define F_REGEXPLODE                   (360)
#define F_SEND_ERQ                     (361)
#define F_SEND_UDP                     (362)
#define F_STRRSTR                      (363)
#define F_STRSTR                       (364)
#define F_WRITE_BYTES                  (365)
#define F_WRITE_FILE                   (366)

/* --- efun4s --- */

#define F_REGREPLACE                   (367)

/* --- vefuns --- */

#define F_ADD_ACTION                   (368)
#define F_ALL_ENVIRONMENT              (369)
#define F_ALLOCATE                     (370)
#define F_APPLY                        (371)
#define F_BIND_LAMBDA                  (372)
#define F_CALL_DIRECT_RESOLVED         (373)
#define F_CALL_OUT                     (374)
#define F_CALL_RESOLVED                (375)
#define F_CLONES                       (376)
#define F_COMMAND                      (377)
#define F_COPY_BITS                    (378)
#define F_DEEP_INVENTORY               (379)
#define F_ED                           (380)
#define F_ENVIRONMENT                  (381)
#define F_FILTER                       (382)
#define F_FILTER_INDICES               (383)
#define F_FILTER_OBJECTS               (384)
#define F_FIND_INPUT_TO                (385)
#define F_FUNCALL                      (386)
#define F_FUNCTION_EXISTS              (387)
#define F_GARBAGE_COLLECTION           (388)
#define F_GET_TYPE_INFO                (389)
#define F_HASH                         (390)
#define F_INCLUDE_LIST                 (391)
#define F_INHERIT_LIST                 (392)
#define F_INPUT_TO                     (393)
#define F_LIMITED                      (394)
#define F_M_ADD                        (395)
#define F_M_CONTAINS                   (396)
#define F_MAP                          (397)
#define F_MAP_INDICES                  (398)
#define F_MAP_OBJECTS                  (399)
#define F_MAX                          (400)
#define F_MD5                          (401)
#define F_MEMBER                       (402)
#define F_MIN                          (403)
#define F_MKMAPPING                    (404)
#define F_OBJECTS                      (405)
#define F_PRESENT                      (406)
#define F_PRESENT_CLONE                (407)
#define F_PRINTF                       (408)
#define F_READ_BYTES                   (409)
#define F_READ_FILE                    (410)
#define F_REGMATCH                     (411)
#define F_REMOVE_INPUT_TO              (412)
#define F_REPLACE_PROGRAM              (413)
#define F_RMEMBER                      (414)
#define F_SAVE_OBJECT                  (415)
#define F_SAVE_VALUE                   (416)
#define F_SAY                          (417)
#define F_SHA1                         (418)
#define F_SNOOP                        (419)
#define F_SORT_ARRAY                   (420)
#define F_SPRINTF                      (421)
#define F_STRFTIME                     (422)
#define F_TELL_ROOM                    (423)
#define F_TERMINAL_COLOUR              (424)
#define F_TO_STRUCT                    (425)
#define F_TRIM                         (426)
#define F_UNIQUE_ARRAY                 (427)
#define F_VARIABLE_EXISTS              (428)
#define F_WALK_MAPPING                 (429)

/************************************************************************/

#endif /* INSTRS_H__ */
